name: Test

on: [push, pull_request]

jobs:
  tests:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: '**/requirements.txt'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Test File
        run: |
          wget https://github.com/lah7/sims2-4k-ui-patch/files/10831338/ui.package.zip
          mv ui.package.zip tests/files/ui.package.xz
          xz -d tests/files/ui.package.xz

      - name: Run Unit Tests
        run: |
          python3 -m unittest discover tests/ -v

  tests_win:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: '**/requirements.txt'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Test File
        run: |
          Invoke-WebRequest -Uri "https://github.com/lah7/sims2-4k-ui-patch/files/10831338/ui.package.zip" -OutFile "ui.package.zip"
          Move-Item -Path "ui.package.zip" -Destination "tests/files/ui.package.xz"
          cd tests/files
          7z x ui.package.xz

      - name: Run Unit Tests
        run: |
          python -m unittest discover tests/ -v
