name: Test

on: [push, pull_request]

jobs:
  tests:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
            submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: '**/requirements.txt'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python3 -m unittest discover tests/ -v

  tests_win:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
            submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: '**/requirements.txt'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m unittest discover tests/ -v
